### ISSUE TITLE
Implement Multiply function

### ISSUE THREAD

**Issue by gus6615** [EDGE-King/King#2]
### Description

Implement Multiply function

### To-do

- [ ] Get 2 numbers (A, B) from user.
- [ ] Multiply A * B and print value.
- [ ] execute for 10 loops.
