### ISSUE TITLE
Implement Add Function

### ISSUE THREAD

**Issue by sehyuk02** [EDGE-King/King#4]
###Description
Implement Add Function for Four arithmetic operation

###TO-DO
- [ ] Implement Add Function
- [ ] Continue Add Function
- [ ] Move to Subtract Function
